rawdata:
        Pacbio:
                - "sequence"
        HiC:
                - "sequence"

parameters:
        scaffolding:
                HiC:
                        part: 16


purge_level:
        0
